### ISSUE TITLE
FR: logging conversation to file

### ISSUE THREAD

**Issue by Arek-Arek** [xavery/czateria#1]
Hi!
Thanks for nice czat client :)
I'd like to ask you would it be possible for you to add logging to file private messages and channel messages?

**Comment by Arek-Arek** [comment]
Even more, it would be nice to write all events to file (join, leaves from/to room), with timestamp. I found that ChatSession::onTextMessageReceived is a place where all happens but this is all I can do with my C++ skills.

**Comment by Arek-Arek** [comment]
You mentioned that you are thinking about this issue. Could you share with idea you have?

**Comment by xavery** [comment]
It's not that I'm "thinking" oh so intensively, it's just that I wouldn't like this to be "bolted onto" the rest of the library. The simplest approach would be to have a logger-like object (or even just a `QFile` that's written to) attached to every `ChatSession`, but this would unnecessarily extend its responsibilities to logging. Seeing how we already have a kind-of event abstract interface due to the fact that most (if not all) network events are exposed as signals to the application, it would make more sense to shift that responsibility there. So the idea is there (it's not like it's rocket science after all), I just don't have the will/time to sit down and actually make it a reality.
Besides, functionality like that would have to be configurable - you might want to have different set of logged events, different locations, or different formatting strings per channel, per login session, and all that. This means that having even a very basic settings window would be desirable, which currently doesn't exist either.

**Comment by Arek-Arek** [comment]
I'm using czateria in this way:  I pipe debug log to sed (it removes timestamp and word debug), next I use jq to add field "date" with value now() to json, next I use `logger` with tcp connection to rsyslog (messages are too big for udp or socket). Rsyslog save messages from ui to file, next I tail log, grep, sed, after this I have flash bell on ssh console when somebody write to me :)
I have additional tail/grep to notify me when friend login to chat.
This is how I made logging and `it works for me` :)
Because I use more than one nickname this log doesn't contains information which nickname wrote to which nickname. This is why I asked you for adding additional information to debug log. But this additional information are outside of json. In debug log this is correct but when I thonk about user log from czateria-ui this mix is inconvenient, because this is mix of two formats.
So debug log is almost enough for me to solve logging problem. 
If I could get json with all mentioned infromation (current time, which nicknames talk to selves) I wuold be happy with it. Probably it would be possible to reuse DEBUG_LOG mechanism to achieve it.
But it is not general solution, other users, probably, won't be happy with it :(

**Comment by Arek-Arek** [comment]
Wow, wow! Thank you!
