### ISSUE TITLE
new url for avatars

### ISSUE THREAD

**Issue by marcin-github** [xavery/czateria#89]
Hello,
there is new schema of urls in avatars:

```
$ curl -I https://qan.interia.pl/chat/applet/chat_resources/images/avatars/users/avatar_xxxxxxxxxxxxxxxx.jpg
HTTP/1.0 302 Moved Temporarily
Date: Thu, 22 Oct 2020 09:02:50 GMT
Server: IPL/2.1
Location: https://i.iplsc.com/-/xxxxxxxxxxxxxxxx-C125.jpg
Content-Type: text/html; charset=iso-8859-1
X-Cache: MISS from IPL/2.1
X-Cache-Lookup: MISS from IPL/2.1:80
Connection: keep-alive
```

**Comment by xavery** [comment]
Should be fine now. It was enough to turn on redirections for the `QNetworkRequest` object in order to make it work, as well as add support for 23-character avatar IDs I've seen with some users. However, the avatars returned from the new server are always scaled to some absurdly large size for some reason. I changed the code to always display them as 120x120 pixels, like the site does.

**Comment by marcin-github** [comment]
Thank you.
